### ISSUE TITLE
ファンエラーが発生します

### ISSUE THREAD

**Issue by kaneko-sora** [goripon1905/Allide-Telesis-fan-script#1]
このスクリプトを実行するとファンエラーが発生してしまいます。
何が問題ですか？

**Comment by goripon1905** [comment]
おそらく使用しているシステムバージョンが古いのでディレクトリ構成が異なっているものだと思われます。
アライドテレシスのサイトから最新バージョンをダウンロードしてアップデートを実施することをオススメします。
(セキュリティ面でもアップデートしたほうが良いです)
